[versions]
java = "21"
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
jooq = "3.20.0"
flyway = "11.11.0"
h2 = "2.3.232"
spotless = "8.3.0"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-webmvc-test" }
spring-boot-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient" }
flyway-core = { module = "org.flywaydb:flyway-core" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
assertj-core = { module = "org.assertj:assertj-core" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-meta = { module = "org.jooq:jooq-meta", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management-plugin = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
flyway-plugin = { id = "org.flywaydb.flyway", version.ref = "flyway" }
jooq-codegen-gradle = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }